<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bahan_baku extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bahan_baku_model');
    } 

    /*
     * Listing of bahan_baku
     */
    function index()
    {
        $data['bahan_baku'] = $this->Bahan_baku_model->get_all_bahan_baku();
        
        $data['_view'] = 'bahan_baku/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new bahan_baku
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('jumlah','Jumlah','required|integer|greater_than[0]');
		$this->form_validation->set_rules('nama','Nama','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'jumlah' => $this->input->post('jumlah'),
				'nama' => $this->input->post('nama'),
            );
            
            $bahan_baku_id = $this->Bahan_baku_model->add_bahan_baku($params);
            redirect('bahan_baku/index');
        }
        else
        {            
            $data['_view'] = 'bahan_baku/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a bahan_baku
     */
    function edit($id_bahanbaku)
    {   
        // check if the bahan_baku exists before trying to edit it
        $data['bahan_baku'] = $this->Bahan_baku_model->get_bahan_baku($id_bahanbaku);
        
        if(isset($data['bahan_baku']['id_bahanbaku']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('jumlah','Jumlah','required|integer|greater_than[0]');
			$this->form_validation->set_rules('nama','Nama','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'jumlah' => $this->input->post('jumlah'),
					'nama' => $this->input->post('nama'),
                );

                $this->Bahan_baku_model->update_bahan_baku($id_bahanbaku,$params);            
                redirect('bahan_baku/index');
            }
            else
            {
                $data['_view'] = 'bahan_baku/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The bahan_baku you are trying to edit does not exist.');
    } 

    /*
     * Deleting bahan_baku
     */
    function remove($id_bahanbaku)
    {
        $bahan_baku = $this->Bahan_baku_model->get_bahan_baku($id_bahanbaku);

        // check if the bahan_baku exists before trying to delete it
        if(isset($bahan_baku['id_bahanbaku']))
        {
            $this->Bahan_baku_model->delete_bahan_baku($id_bahanbaku);
            redirect('bahan_baku/index');
        }
        else
            show_error('The bahan_baku you are trying to delete does not exist.');
    }
    
}
