<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Dashboard extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
    }

    function indsex()
    {

        if ($this->session->userdata('username') == "") {
            redirect('app/login');
        }


        $data['_view'] = 'dashboard';
        $this->load->view('login', $data);
    }
}
