<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Manager extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Manager_model');
    }

    /*
     * Listing of manager
     */
    function index()
    {
        $data['manager'] = $this->Manager_model->get_all_manager();
        $data['_view'] = 'manager/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new manager
     */
    function add()
    {
        $this->load->library('form_validation');

        $this->form_validation->set_rules('email', 'Email', 'required|max_length[99]|valid_email');
        $this->form_validation->set_rules('nama', 'Nama', 'required');

        if ($this->form_validation->run()) {
            $params = array(
                'id_perusahaan' => $this->input->post('id_perusahaan'),
                'email' => $this->input->post('email'),
                'nama' => $this->input->post('nama'),
            );

            $manager_id = $this->Manager_model->add_manager($params);
            redirect('manager/index');
        } else {
            $this->load->model('Perusahaan_model');
            $data['all_perusahaan'] = $this->Perusahaan_model->get_all_perusahaan();

            $data['_view'] = 'manager/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a manager
     */
    function edit($id_manager)
    {
        // check if the manager exists before trying to edit it
        $data['manager'] = $this->Manager_model->get_manager($id_manager);

        if (isset($data['manager']['id_manager'])) {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('email', 'Email', 'required|max_length[99]|valid_email');
            $this->form_validation->set_rules('nama', 'Nama', 'required');

            if ($this->form_validation->run()) {
                $params = array(
                    'id_perusahaan' => $this->input->post('id_perusahaan'),
                    'email' => $this->input->post('email'),
                    'nama' => $this->input->post('nama'),
                );

                $this->Manager_model->update_manager($id_manager, $params);
                redirect('manager/index');
            } else {
                $this->load->model('Perusahaan_model');
                $data['all_perusahaan'] = $this->Perusahaan_model->get_all_perusahaan();

                $data['_view'] = 'manager/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The manager you are trying to edit does not exist.');
    }

    /*
     * Deleting manager
     */
    function remove($id_manager)
    {
        $manager = $this->Manager_model->get_manager($id_manager);

        // check if the manager exists before trying to delete it
        if (isset($manager['id_manager'])) {
            $this->Manager_model->delete_manager($id_manager);
            redirect('manager/index');
        } else
            show_error('The manager you are trying to delete does not exist.');
    }
}
