<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Model extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Model_model');
    } 

    /*
     * Listing of model
     */
    function index()
    {
        $data['model'] = $this->Model_model->get_all_model();
        
        $data['_view'] = 'model/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new model
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama','Nama','required');
		$this->form_validation->set_rules('id_bahanbaku','Id Bahanbaku','required');
		$this->form_validation->set_rules('id_perusahaan','Id Perusahaan','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'id_bahanbaku' => $this->input->post('id_bahanbaku'),
				'id_perusahaan' => $this->input->post('id_perusahaan'),
				'nama' => $this->input->post('nama'),
            );
            
            $model_id = $this->Model_model->add_model($params);
            redirect('model/index');
        }
        else
        {
			$this->load->model('Bahan_baku_model');
			$data['all_bahan_baku'] = $this->Bahan_baku_model->get_all_bahan_baku();

			$this->load->model('Perusahaan_model');
			$data['all_perusahaan'] = $this->Perusahaan_model->get_all_perusahaan();
            
            $data['_view'] = 'model/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a model
     */
    function edit($id_model)
    {   
        // check if the model exists before trying to edit it
        $data['model'] = $this->Model_model->get_model($id_model);
        
        if(isset($data['model']['id_model']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama','Nama','required');
			$this->form_validation->set_rules('id_bahanbaku','Id Bahanbaku','required');
			$this->form_validation->set_rules('id_perusahaan','Id Perusahaan','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'id_bahanbaku' => $this->input->post('id_bahanbaku'),
					'id_perusahaan' => $this->input->post('id_perusahaan'),
					'nama' => $this->input->post('nama'),
                );

                $this->Model_model->update_model($id_model,$params);            
                redirect('model/index');
            }
            else
            {
				$this->load->model('Bahan_baku_model');
				$data['all_bahan_baku'] = $this->Bahan_baku_model->get_all_bahan_baku();

				$this->load->model('Perusahaan_model');
				$data['all_perusahaan'] = $this->Perusahaan_model->get_all_perusahaan();

                $data['_view'] = 'model/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The model you are trying to edit does not exist.');
    } 

    /*
     * Deleting model
     */
    function remove($id_model)
    {
        $model = $this->Model_model->get_model($id_model);

        // check if the model exists before trying to delete it
        if(isset($model['id_model']))
        {
            $this->Model_model->delete_model($id_model);
            redirect('model/index');
        }
        else
            show_error('The model you are trying to delete does not exist.');
    }
    
}
