<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Persediaan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Persediaan_model');
    }

    /*
     * Listing of persediaan
     */
    function index()
    {
        if ($this->session->userdata('username') == "") {
            redirect('app/login');
        }
        if ($this->session->userdata('status') == "manager") {
            $data['persediaan'] = $this->Persediaan_model->get_all_persediaan();

            $data['_view'] = 'persediaan/index';
            $this->load->view('layouts/main', $data);
        }
        if ($this->session->userdata('status') == "karyawan") {

            $data['persediaan'] = $this->Persediaan_model->daftar();
            $data['_view'] = 'persediaan/daftar';
            $this->load->view('krywn/main', $data);
        }
    }

    /*
     * Adding a new persediaan
     */
    function add()
    {
        $this->load->library('form_validation');

        $this->form_validation->set_rules('id_bahanbaku', 'Id Bahanbaku', 'required');
        $this->form_validation->set_rules('jumlah', 'Jumlah', 'required|integer|greater_than[0]');
        $this->form_validation->set_rules('id_perusahaan', 'Id Perusahaan', 'required');

        if ($this->form_validation->run()) {
            $params = array(
                'id_perusahaan' => $this->input->post('id_perusahaan'),
                'id_bahanbaku' => $this->input->post('id_bahanbaku'),
                'jumlah' => $this->input->post('jumlah'),
            );

            $persediaan_id = $this->Persediaan_model->add_persediaan($params);
            redirect('persediaan/index');
        } else {
            $this->load->model('Perusahaan_model');
            $data['all_perusahaan'] = $this->Perusahaan_model->get_all_perusahaan();

            $this->load->model('Bahan_baku_model');
            $data['all_bahan_baku'] = $this->Bahan_baku_model->get_all_bahan_baku();

            $data['_view'] = 'persediaan/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a persediaan
     */
    function edit($id_persediaan)
    {
        // check if the persediaan exists before trying to edit it
        $data['persediaan'] = $this->Persediaan_model->get_persediaan($id_persediaan);

        if (isset($data['persediaan']['id_persediaan'])) {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('id_bahanbaku', 'Id Bahanbaku', 'required');
            $this->form_validation->set_rules('jumlah', 'Jumlah', 'required|integer|greater_than[0]');
            $this->form_validation->set_rules('id_perusahaan', 'Id Perusahaan', 'required');

            if ($this->form_validation->run()) {
                $params = array(
                    'id_perusahaan' => $this->input->post('id_perusahaan'),
                    'id_bahanbaku' => $this->input->post('id_bahanbaku'),
                    'jumlah' => $this->input->post('jumlah'),
                );

                $this->Persediaan_model->update_persediaan($id_persediaan, $params);
                redirect('persediaan/index');
            } else {
                $this->load->model('Perusahaan_model');
                $data['all_perusahaan'] = $this->Perusahaan_model->get_all_perusahaan();

                $this->load->model('Bahan_baku_model');
                $data['all_bahan_baku'] = $this->Bahan_baku_model->get_all_bahan_baku();

                $data['_view'] = 'persediaan/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The persediaan you are trying to edit does not exist.');
    }

    /*
     * Deleting persediaan
     */
    function remove($id_persediaan)
    {
        $persediaan = $this->Persediaan_model->get_persediaan($id_persediaan);

        // check if the persediaan exists before trying to delete it
        if (isset($persediaan['id_persediaan'])) {
            $this->Persediaan_model->delete_persediaan($id_persediaan);
            redirect('persediaan/index');
        } else
            show_error('The persediaan you are trying to delete does not exist.');
    }
}
