<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perusahaan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Perusahaan_model');
    } 

    /*
     * Listing of perusahaan
     */
    function index()
    {
        $data['perusahaan'] = $this->Perusahaan_model->get_all_perusahaan();
        
        $data['_view'] = 'perusahaan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new perusahaan
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama','Nama','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nama' => $this->input->post('nama'),
            );
            
            $perusahaan_id = $this->Perusahaan_model->add_perusahaan($params);
            redirect('perusahaan/index');
        }
        else
        {            
            $data['_view'] = 'perusahaan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a perusahaan
     */
    function edit($id_perusahaan)
    {   
        // check if the perusahaan exists before trying to edit it
        $data['perusahaan'] = $this->Perusahaan_model->get_perusahaan($id_perusahaan);
        
        if(isset($data['perusahaan']['id_perusahaan']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama','Nama','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nama' => $this->input->post('nama'),
                );

                $this->Perusahaan_model->update_perusahaan($id_perusahaan,$params);            
                redirect('perusahaan/index');
            }
            else
            {
                $data['_view'] = 'perusahaan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The perusahaan you are trying to edit does not exist.');
    } 

    /*
     * Deleting perusahaan
     */
    function remove($id_perusahaan)
    {
        $perusahaan = $this->Perusahaan_model->get_perusahaan($id_perusahaan);

        // check if the perusahaan exists before trying to delete it
        if(isset($perusahaan['id_perusahaan']))
        {
            $this->Perusahaan_model->delete_perusahaan($id_perusahaan);
            redirect('perusahaan/index');
        }
        else
            show_error('The perusahaan you are trying to delete does not exist.');
    }
    
}
