<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class User extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');
    }

    /*
     * Listing of upah_karyawan
     */
    function index()
    {
        if ($this->session->userdata('status') == "manager") {
            $data['user'] = $this->User_model->get_all_user();

            $data['_view'] = 'user/index';
            $this->load->view('layouts/main', $data);
        } else {
            $this->load->view('siapa');
        }
    }

    /*
     * Adding a new upah_karyawan
     */
    function add()
    {
        if ($this->session->userdata('status') == "manager") {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('username', 'Username', 'required');
            $this->form_validation->set_rules('password', 'Password', 'required');
            $this->form_validation->set_rules('nama', 'Nama', 'required');
            $this->form_validation->set_rules('pemilik', 'Pemilik', 'required');
            $this->form_validation->set_rules('level', 'Level', 'required');

            if ($this->form_validation->run()) {
                $params = array(
                    'username' => $this->input->post('username'),
                    'password' => md5($this->input->post('password')),
                    'nama' => $this->input->post('nama'),
                    'pemilik' => $this->input->post('pemilik'),
                    'level' => $this->input->post('level'),
                );

                $user_id = $this->User_model->add_user($params);
                redirect('user/index');
            } else {
                $this->load->model('Karyawan_model');
                $data['all_karyawan'] = $this->Karyawan_model->get_all_karyawan();

                $data['_view'] = 'user/add';
                $this->load->view('layouts/main', $data);
            }
        } else {
            $this->load->view('siapa');
        }
    }

    /*
     * Editing a upah_karyawan
     */
    function edit($id_user)
    {
        if ($this->session->userdata('status') == "manager") {
            // check if the upah_karyawan exists before trying to edit it
            $data['user'] = $this->User_model->get_user($id_user);

            if (isset($data['user']['id_user'])) {
                $this->load->library('form_validation');

                $this->form_validation->set_rules('username', 'Username', 'required');
                $this->form_validation->set_rules('password', 'Password', 'required');
                $this->form_validation->set_rules('nama', 'Nama', 'required');
                $this->form_validation->set_rules('pemilik', 'Pemilik', 'required');
                // $this->form_validation->set_rules('level', 'Level', 'required');

                if ($this->form_validation->run()) {
                    $params = array(
                        'username' => $this->input->post('username'),
                        'password' => md5($this->input->post('password')),
                        'nama' => $this->input->post('nama'),
                        'pemilik' => $this->input->post('pemilik'),
                        // 'level' => $this->input->post('level'),
                    );

                    $this->User_model->update_user($id_user, $params);
                    redirect('user/index');
                } else {
                    $this->load->model('Karyawan_model');
                    $data['all_karyawan'] = $this->Karyawan_model->get_all_karyawan();

                    $data['_view'] = 'user/edit';
                    $this->load->view('layouts/main', $data);
                }
            } else
                show_error('The user you are trying to edit does not exist.');
        } else {
            $this->load->view('siapa');
        }
    }

    /*
     * Deleting upah_karyawan
     */
    function remove($id_user)
    {
        if ($this->session->userdata('status') == "manager") {

            $user = $this->User_model->get_user($id_user);

            // check if the upah_karyawan exists before trying to delete it
            if (isset($user['id_user'])) {
                $this->User_model->delete_user($id_user);
                redirect('user/index');
            } else
                show_error('The user you are trying to delete does not exist.');
        } else {
            $this->load->view('siapa');
        }
    }
}
