<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Karyawan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get karyawan by id_karyawan
     */
    function get_karyawan($id_karyawan)
    {
        return $this->db->get_where('karyawan', array('id_karyawan' => $id_karyawan))->row_array();
    }

    /*
     * Get all karyawan
     */
    function get_all_karyawan()
    {
        //Panggil Nama
        $this->db->select('a.id_karyawan,b.nama as id_perusahaan,a.nama,c.keterangan as id_shift,d.nama as id_mesin');
        $this->db->from('karyawan a');
        $this->db->join('perusahaan b', 'a.id_perusahaan = b.id_perusahaan');
        $this->db->join('shift c', 'a.id_shift=c.id_shift');
        $this->db->join('mesin d', 'a.id_mesin=d.id_mesin');
        //Tampilkan
        $this->db->group_by('id_karyawan', 'desc');
        return $this->db->get('karyawan')->result_array();
        // $query = $this->db->get();
        // $result = $query->result_array();

        // if (!empty($result)) {
        //     return $result;
        // }
    }

    /*
     * function to add new karyawan
     */
    function add_karyawan($params)
    {
        $this->db->insert('karyawan', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update karyawan
     */
    function update_karyawan($id_karyawan, $params)
    {
        $this->db->where('id_karyawan', $id_karyawan);
        return $this->db->update('karyawan', $params);
    }

    /*
     * function to delete karyawan
     */
    function delete_karyawan($id_karyawan)
    {
        return $this->db->delete('karyawan', array('id_karyawan' => $id_karyawan));
    }
}
