<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Manager_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get manager by id_manager
     */
    function get_manager($id_manager)
    {
        return $this->db->get_where('manager', array('id_manager' => $id_manager))->row_array();
    }

    /*
     * Get all manager
     */
    function get_all_manager()
    {
        //Panggil Nama
        $this->db->select('a.id_manager,a.nama, a.email,b.nama as id_perusahaan');
        $this->db->from('manager a');
        $this->db->join('perusahaan b', 'a.id_perusahaan=b.id_perusahaan');
        //Tampilkan

        //Coba
        // $query = $this->db->get();
        // $result = $query->result_array();

        // if (!empty($result)) {
        //     return $result;
        // }


        $this->db->group_by('id_manager', 'desc');
        return $this->db->get('manager')->result_array();
    }

    /*
     * function to add new manager
     */
    function add_manager($params)
    {
        $this->db->insert('manager', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update manager
     */
    function update_manager($id_manager, $params)
    {
        $this->db->where('id_manager', $id_manager);
        return $this->db->update('manager', $params);
    }

    /*
     * function to delete manager
     */
    function delete_manager($id_manager)
    {
        return $this->db->delete('manager', array('id_manager' => $id_manager));
    }
}
