<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Model_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get model by id_model
     */
    function get_model($id_model)
    {
        return $this->db->get_where('model', array('id_model' => $id_model))->row_array();
    }

    /*
     * Get all model
     */
    function get_all_model()
    {
        //Panggil Nama
        $this->db->select('a.id_model,a.nama,b.nama as id_bahanbaku,c.nama as id_perusahaan');
        $this->db->from('model a');
        $this->db->join('bahan_baku b', 'a.id_bahanbaku=b.id_bahanbaku');
        $this->db->join('perusahaan c', 'a.id_perusahaan=c.id_perusahaan');
        //Tampilkan
        $this->db->group_by('id_model', 'desc');
        return $this->db->get('model')->result_array();
        // $query = $this->db->get();
        // $result = $query->result_array();

        // if (!empty($result)) {
        //     return $result;
        // }
    }

    /*
     * function to add new model
     */
    function add_model($params)
    {
        $this->db->insert('model', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update model
     */
    function update_model($id_model, $params)
    {
        $this->db->where('id_model', $id_model);
        return $this->db->update('model', $params);
    }

    /*
     * function to delete model
     */
    function delete_model($id_model)
    {
        return $this->db->delete('model', array('id_model' => $id_model));
    }
}
