<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Persediaan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get persediaan by id_persediaan
     */
    function get_persediaan($id_persediaan)
    {
        return $this->db->get_where('persediaan', array('id_persediaan' => $id_persediaan))->row_array();
    }

    /*
     * Get all persediaan
     */
    function get_all_persediaan()
    {
        //Panggil Nama
        $this->db->select('a.id_persediaan,a.jumlah,b.nama as nama_perusahaan, c.nama as nama_bahanbaku');
        $this->db->from('persediaan a');
        $this->db->join('perusahaan b', 'a.id_perusahaan=b.id_perusahaan');
        $this->db->join('bahan_baku c', 'a.id_bahanbaku=c.id_bahanbaku');
        //Tampilkan
        $this->db->group_by('id_persediaan', 'desc');
        return $this->db->get('persediaan')->result_array();
        // $query = $this->db->get();
        // $result = $query->result_array();

        // if (!empty($result)) {
        //     return $result;
        // }
    }
    //Daftar
    function daftar()
    {
        // $query = $this->db->query('SELECT 
        // persediaan.id_persediaan,
        // bahan_baku.nama as nama,
        // persediaan.jumlah as tersedia,
        // IFNULL((bahan_baku.jumlah*SUM(pesanan.jumlah)),0) as digunakan,
        // IFNULL((persediaan.jumlah-(bahan_baku.jumlah*SUM(pesanan.jumlah))),persediaan.jumlah) as sisa
        // FROM `persediaan` JOIN bahan_baku ON persediaan.id_bahanbaku=bahan_baku.id_bahanbaku
        // LEFT JOIN model ON model.id_bahanbaku=bahan_baku.id_bahanbaku
        // LEFT JOIN pesanan ON pesanan.id_model=model.id_model
        // GROUP BY persediaan.id_persediaan');
        $query = $this->db->query('SELECT 
        persediaan.id_persediaan,
        bahan_baku.nama as nama,
        persediaan.jumlah as tersedia,
        IFNULL((SUM(produksi.potong_terselesaikan)*bahan_baku.jumlah),0) as digunakan,
        IFNULL((persediaan.jumlah-(SUM(produksi.potong_terselesaikan)*bahan_baku.jumlah)),persediaan.jumlah) as sisa
        FROM `persediaan` LEFT JOIN bahan_baku ON persediaan.id_bahanbaku=bahan_baku.id_bahanbaku
        LEFT JOIN model ON model.id_bahanbaku=bahan_baku.id_bahanbaku
        LEFT JOIN pesanan ON pesanan.id_model=model.id_model
        LEFT JOIN produksi ON pesanan.id_pesanan=produksi.id_pesanan
        GROUP BY persediaan.id_persediaan');
        return $query->result_array();
    }
    /*
     * function to add new persediaan
     */
    function add_persediaan($params)
    {
        $this->db->insert('persediaan', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update persediaan
     */
    function update_persediaan($id_persediaan, $params)
    {
        $this->db->where('id_persediaan', $id_persediaan);
        return $this->db->update('persediaan', $params);
    }

    /*
     * function to delete persediaan
     */
    function delete_persediaan($id_persediaan)
    {
        return $this->db->delete('persediaan', array('id_persediaan' => $id_persediaan));
    }
}
