<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perusahaan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get perusahaan by id_perusahaan
     */
    function get_perusahaan($id_perusahaan)
    {
        return $this->db->get_where('perusahaan',array('id_perusahaan'=>$id_perusahaan))->row_array();
    }
        
    /*
     * Get all perusahaan
     */
    function get_all_perusahaan()
    {
        $this->db->order_by('id_perusahaan', 'desc');
        return $this->db->get('perusahaan')->result_array();
    }
        
    /*
     * function to add new perusahaan
     */
    function add_perusahaan($params)
    {
        $this->db->insert('perusahaan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update perusahaan
     */
    function update_perusahaan($id_perusahaan,$params)
    {
        $this->db->where('id_perusahaan',$id_perusahaan);
        return $this->db->update('perusahaan',$params);
    }
    
    /*
     * function to delete perusahaan
     */
    function delete_perusahaan($id_perusahaan)
    {
        return $this->db->delete('perusahaan',array('id_perusahaan'=>$id_perusahaan));
    }
}
