<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Produksi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get produksi by id_produksi
     */
    function get_produksi($id_produksi)
    {
        return $this->db->get_where('produksi', array('id_produksi' => $id_produksi))->row_array();
    }

    /*
     * Get all produksi
     */
    function get_all_produksi()
    {
        //Panggil Nama
        $this->db->select('a.ket,a.id_produksi,a.nama,a.potong_terselesaikan,a.tanggal_produksi,b.nama as id_pesanan,c.nama as id_karyawan');
        $this->db->from('produksi a');
        $this->db->join('pesanan b', 'a.id_pesanan=b.id_pesanan');
        $this->db->join('karyawan c', 'a.id_karyawan=c.id_karyawan');
        //Tampilkan
        // $query = $this->db->get();
        // $result = $query->result_array();

        // if (!empty($result)) {
        //     return $result;
        // }
        $this->db->group_by('id_produksi', 'desc');
        return $this->db->get('produksi')->result_array();
    }
    function prod()
    {
        $saya = ucfirst($_SESSION["pemilik"]);
        $query = $this->db->query("SELECT
        (pesanan.upah_perpotong*produksi.potong_terselesaikan) as upah,
        produksi.id_produksi as id_produksi,
        produksi.nama as nama,
        produksi.ket as ket,
        produksi.potong_terselesaikan as potong_terselesaikan,
        produksi.tanggal_produksi as tanggal_produksi,
        pesanan.nama as id_pesanan,
        karyawan.nama as id_karyawan
        FROM produksi JOIN pesanan ON produksi.id_pesanan=pesanan.id_pesanan
        JOIN karyawan ON produksi.id_karyawan=karyawan.id_karyawan
        WHERE produksi.id_karyawan='$saya' AND produksi.ket='BELUM TERVERIFIKASI'");
        return $query->result_array();
    }
    function produdh()
    {
        $saya = ucfirst($_SESSION["pemilik"]);
        $query = $this->db->query("SELECT
        (pesanan.upah_perpotong*produksi.potong_terselesaikan) as upah,
        produksi.id_produksi as id_produksi,
        produksi.nama as nama,
        produksi.ket as ket,
        produksi.potong_terselesaikan as potong_terselesaikan,
        produksi.tanggal_produksi as tanggal_produksi,
        pesanan.nama as id_pesanan,
        karyawan.nama as id_karyawan
        FROM produksi JOIN pesanan ON produksi.id_pesanan=pesanan.id_pesanan
        JOIN karyawan ON produksi.id_karyawan=karyawan.id_karyawan
        WHERE produksi.id_karyawan='$saya' AND produksi.ket='TERVERIFIKASI'");
        return $query->result_array();
    }
    function d_verif()
    {
        $query = $this->db->query("SELECT
        (pesanan.upah_perpotong*produksi.potong_terselesaikan) as upah,
        produksi.id_produksi as id_produksi,
        produksi.nama as nama,
        produksi.ket as ket,
        produksi.potong_terselesaikan as potong_terselesaikan,
        produksi.tanggal_produksi as tanggal_produksi,
        pesanan.nama as id_pesanan,
        karyawan.nama as id_karyawan
        FROM produksi JOIN pesanan ON produksi.id_pesanan=pesanan.id_pesanan
        JOIN karyawan ON produksi.id_karyawan=karyawan.id_karyawan
        WHERE produksi.ket='BELUM TERVERIFIKASI'");
        return $query->result_array();
    }

    function verif_ok($id_produksi)
    {
        $ket = "TERVERIFIKASI";
        return $this->db->query("UPDATE produksi SET ket='$ket' WHERE id_produksi = '$id_produksi'");
    }
    //Tambah dan List
    // function tambah()
    // {
    //     $this->db->insert('produksi', $params);
    //     return $this->db->insert_id();
    //     $this->db->select('a.id_produksi,a.nama,a.potong_terselesaikan,a.tanggal_produksi,b.nama as id_pesanan,c.nama as id_karyawan');
    //     $this->db->from('produksi a');
    //     $this->db->join('pesanan b', 'a.id_pesanan=b.id_pesanan');
    //     $this->db->join('karyawan c', 'a.id_karyawan=c.id_karyawan');
    //     $this->db->group_by('id_produksi');
    //     return $this->db->get('produksi')->result_array();
    // }

    /*
     * function to add new produksi
     */
    function add_produksi($params)
    {
        $this->db->insert('produksi', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update produksi
     */
    function update_produksi($id_produksi, $params)
    {
        $this->db->where('id_produksi', $id_produksi);
        return $this->db->update('produksi', $params);
    }

    /*
     * function to delete produksi
     */
    function delete_produksi($id_produksi)
    {
        return $this->db->delete('produksi', array('id_produksi' => $id_produksi));
    }
}
