<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Shift_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get shift by id_shift
     */
    function get_shift($id_shift)
    {
        return $this->db->get_where('shift',array('id_shift'=>$id_shift))->row_array();
    }
        
    /*
     * Get all shift
     */
    function get_all_shift()
    {
        $this->db->order_by('id_shift', 'desc');
        return $this->db->get('shift')->result_array();
    }
        
    /*
     * function to add new shift
     */
    function add_shift($params)
    {
        $this->db->insert('shift',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update shift
     */
    function update_shift($id_shift,$params)
    {
        $this->db->where('id_shift',$id_shift);
        return $this->db->update('shift',$params);
    }
    
    /*
     * function to delete shift
     */
    function delete_shift($id_shift)
    {
        return $this->db->delete('shift',array('id_shift'=>$id_shift));
    }
}
